create table "public"."test3" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."test3" enable row level security;

CREATE UNIQUE INDEX test3_pkey ON public.test3 USING btree (id);

alter table "public"."test3" add constraint "test3_pkey" PRIMARY KEY using index "test3_pkey";

grant delete on table "public"."test3" to "anon";

grant insert on table "public"."test3" to "anon";

grant references on table "public"."test3" to "anon";

grant select on table "public"."test3" to "anon";

grant trigger on table "public"."test3" to "anon";

grant truncate on table "public"."test3" to "anon";

grant update on table "public"."test3" to "anon";

grant delete on table "public"."test3" to "authenticated";

grant insert on table "public"."test3" to "authenticated";

grant references on table "public"."test3" to "authenticated";

grant select on table "public"."test3" to "authenticated";

grant trigger on table "public"."test3" to "authenticated";

grant truncate on table "public"."test3" to "authenticated";

grant update on table "public"."test3" to "authenticated";

grant delete on table "public"."test3" to "service_role";

grant insert on table "public"."test3" to "service_role";

grant references on table "public"."test3" to "service_role";

grant select on table "public"."test3" to "service_role";

grant trigger on table "public"."test3" to "service_role";

grant truncate on table "public"."test3" to "service_role";

grant update on table "public"."test3" to "service_role";


